---
test:
  ibm_terraform_defaults: &ibm_terraform_defaults
    url: cam-url
    identity_url: cam-identity-url
    cpd_url: cam-cpd-url
    user: CAM_USER
    password: CAM_PASSWORD
  ibm_terraform:
    <<: *ibm_terraform_defaults
